version: '3.2'

services:
    hnd-labs-memcached:
        container_name: api-base-memchached
        image: 'memcached:alpine'

    hnd-labs-mailhog:
        container_name: api-base-mailhog
        image: 'mailhog/mailhog:latest'
        ports:
            - '8889:8025'

    hnd-labs-redis:
        container_name: api-base-redis
        image: 'redis:alpine'

    hnd-labs-webserver:
        image: 'nginx:alpine'
        #user: ${USER_ID:-1000}:${GROUP_ID:-1000}
        working_dir: /data
        container_name: api-base-webserver
        depends_on:
            - hnd-labs-redis
            - hnd-labs-php-fpm
            - hnd-labs-mailhog
            - hnd-labs-memcached
        volumes:
            - .:/data
            - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - '8888:80'
        networks:
            - hndlabs-network
            - backend

    hnd-labs-php-fpm:
        #user: ${USER_ID:-1000}:${GROUP_ID:-1000}
        stdin_open: true
        build:
            context: .
            args:
                USER_ID: ${USER_ID:-1000}
                GROUP_ID: ${GROUP_ID:-1000}
                LARAVEL_ENV: ${LARAVEL_ENV:-prod}
        container_name: api-base-php-fpm
        entrypoint: /data/entrypoint_${LARAVEL_ENV:-prod}.sh
        env_file:
            - .env
        working_dir: /data
        volumes:
            - .:/data
            - /data/vendor
            - /data/storage
            - /etc/group:/etc/group:ro
            - /etc/passwd:/etc/passwd:ro
            - /etc/shadow:/etc/shadow:ro
            - ./.docker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini
        networks:
            - backend
networks:
    backend:
    hndlabs-network:
        external: true
