###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    memcached:
        image: 'memcached:alpine'

    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '8889:8025'

    redis:
        image: 'redis:alpine'

    webserver:
        image: 'nginx:alpine'
        working_dir: /data
        volumes:
            - '.:/data'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8888:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /data
        volumes:
            - '.:/data'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini'
